---
- name: Create keytab directory on ambari server
  file:
    path: /etc/security/keytabs
    state: directory
    mode: 0755

- name: Retrieve ambari.server.keytab
  copy:
    src: /tmp/ambari.server.keytab
    dest: /etc/security/keytabs/ambari.server.keytab
    mode: 0400

- name: Stop ambari server
  command: ambari-server stop

- name: Setup Ambari kerberos JAAS configuration
  command: >
    ambari-server setup-security 
      --security-option=setup-kerberos-jaas
      --jaas-principal="ambari-server@{{ realm }}"
      --jaas-keytab="/etc/security/keytabs/ambari.server.keytab"

- name: Start ambari server
  command: ambari-server start
