- name: Copy krb5.conf
  copy:
    src: /tmp/krb5.conf
    dest: /etc/krb5.conf

- name: Set "default_ccache_name" 
  ini_file:
    path: /etc/krb5.conf 
    section: libdefaults 
    option: default_ccache_name 
    value: FILE:/tmp/krb5cc_%{uid}
