---
- include_tasks: krb01-install.yml
  when: action == "krb_install"

- include_tasks: krb02-add-users-services.yml
  when: action == "krb_add_users_services"

- include_tasks: krb03-ambari-keytab.yml
  when: action == "krb_ambari_keytab"

- include_tasks: krb04-ambari-setup.yml
  when: action == "krb_ambari_setup"

- include_tasks: krb05-generate-keytabs.yml
  when: action == "krb_generate_keytabs"

- include_tasks: krb06-distribute-keytabs.yml
  when: action == "krb_distribute_keytabs"

- include_tasks: krb07-set-krb5-conf.yml
  when: action == "krb_set_krb5_conf"
