---
- name: Download version 9.6
  yum:
    name: "{{ services.POSTGRESQL.url }}"

- name: Install version 9.6
  yum:
    name: [postgresql96, postgresql96-server]

- name: Initiate database
  command: /usr/pgsql-9.6/bin/postgresql96-setup initdb
    creates=/var/lib/pgsql/data/postgresql.conf
  register: reg_initdb
  failed_when: 'reg_initdb is failed and "Data directory is not empty!" not in reg_initdb.stdout'
