---
- name: Download version 10
  yum:
    name: "{{ services.POSTGRESQL.url }}"

- name: Install version 10
  yum:
    name: [postgresql10, postgresql10-server]

- name: Initiate database
  command: /usr/pgsql-10/bin/postgresql-10-setup initdb
    creates=/var/lib/pgsql/data/postgresql.conf
  register: reg_initdb
  failed_when: 'reg_initdb is failed and "Data directory is not empty!" not in reg_initdb.stdout'
