---
- name: Download version 11
  yum:
    name: "{{ services.POSTGRESQL.url }}"

- name: Install version 11
  yum:
    name: [postgresql11, postgresql11-server]

- name: Initiate database
  command: /usr/pgsql-11/bin/postgresql-11-setup initdb
    creates=/var/lib/pgsql/data/postgresql.conf
  register: reg_initdb
  failed_when: 'reg_initdb is failed and "Data directory is not empty!" not in reg_initdb.stdout'
