---
- name: Download and install ambari-server
  yum:
    name: ambari-server

- name: Load the Ambari Server database schema
  shell: PGPASSWORD=ambari psql -U ambari -d ambari -f '/var/lib/ambari-server/resources/Ambari-DDL-Postgres-CREATE.sql'
  become_user: postgres
  ignore_errors: yes

- name: Download PostgreSQL JDBC driver
  get_url:
    url: "{{ platform.HDP.resources.POSTGRESQL_JDBC_DRIVER.url }}"
    dest: "/var/lib/ambari-server/postgresql-jdbc-{{ platform.HDP.resources.POSTGRESQL_JDBC_DRIVER.version }}.jar"

- name: Set jdbc driver
  command: ambari-server setup \
    --jdbc-driver=/var/lib/ambari-server/postgresql-jdbc-{{ platform.HDP.resources.POSTGRESQL_JDBC_DRIVER.version }}.jar \
    --jdbc-db=postgres

- name: Ambari setup
  command: ambari-server setup \
    --database=postgres \
    --databasehost={{ pgsqlserver }} \
    --databaseport=5432 \
    --databasename=ambari \
    --postgresschema=ambarischema \
    --databaseusername=ambari \
    --databasepassword=ambari \
    {{ '--java-home ' ~ JAVA_HOME if JAVA_HOME is defined else '' }} \
    -s

- name: Start ambari-server
  service:
    name: ambari-server
    state: started

- name: open Ambari tcp ports
  iptables:
    chain: INPUT
    jump: ACCEPT
    action: insert
    destination_port: "{{ item }}"
    protocol: tcp 
    ctstate: NEW,ESTABLISHED
  with_items:
    - 8080
    - 8440
    - 8441