---
## Example blueprint playbook
- hosts: ambariserver
  roles:
    # Copy clean blueprint to /tmp/blueprint.json
    # Generate hostgroups with components
    # Register handlers
    - build-blueprint
    # Complete blueprint configurations by calling required roles
    - { role: blueprint-hdfs, when: HDFS is defined }
    - { role: blueprint-zookeeper, when: ZOOKEEPER is defined }
    - { role: blueprint-kafka, when: KAFKA is defined }
    - { role: blueprint-yarn, when: YARN is defined }
    - { role: blueprint-hive, when: HIVE is defined }
    - { role: blueprint-hbase, when: HBASE is defined }
    - { role: blueprint-oozie, when: OOZIE is defined }
    - { role: blueprint-spark2, when: SPARK2 is defined }
    - { role: blueprint-zeppelin, when: ZEPPELIN is defined }
    - { role: blueprint-ranger, when: RANGER is defined }
    # Post blueprint to Ambari API
    - post-blueprint
