---
- hosts: all
  become: true
  become_flags: "-E"
  tasks:
    - name: Configure servers hostnames
      hostname:
        name: "{{ inventory_hostname }}.{{ domain }}"

    - name: Add "ip fqdn shortname" to /etc/hosts
      lineinfile:
        dest: "/etc/hosts"
        line: "{{ hostvars[item]['ansible_host'] }} {{ item }}.{{ domain }} {{ item }}"
        insertbefore: BOF
      with_items: "{{ groups['all'] }}"

    - name: Set Yum repositories
      get_url:
        url: "{{ item.value.source }}"
        dest: "{{ item.value.dest }}"
        force: yes
      with_dict: "{{ repositories }}"

    - name: Install common packages
      yum:
        name: [net-tools, ntp, vim, wget]
        state: latest

    - name: Disable and stop chronyd
      service:
        name: chronyd
        state: stopped
        enabled: no
      register: disable_chronyd
      failed_when: 'disable_chronyd is failed and "Could not find the requested service chronyd" not in disable_chronyd.msg'

    - name: Enable NTPd
      service:
        name: ntpd
        state: started
        enabled: yes
