---
- hosts: ambariserver
  roles:
    - role: kerberos
      action: "krb_install"

- hosts: ipaserver
  become: true
  roles:
    - role: kerberos
      action: "krb_add_users_services"
    - role: kerberos
      action: "krb_ambari_keytab"

- hosts: ambariserver
  become: true
  roles:
    - role: kerberos
      action: "krb_ambari_setup"

- hosts: ipaserver
  become: true
  roles:
    - role: kerberos
      action: "krb_generate_keytabs"

- hosts: all:!ipaserver
  become: true
  roles:
    - role: kerberos
      action: "krb_distribute_keytabs"

- hosts: all
  become: true
  roles:
    - role: kerberos
      action: "krb_set_krb5_conf"

